# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
      - echo Installing source NPM dependencies...
      - echo Installation completed on `date`
artifacts:
  files:
    - package.json
    - package-lock.json
    - node_modules/**/*
    - index.js
    - db.js
    - db.sqlite
